#include "rust/cxx.h"
// Generated by `cxx_build::bridge("src/lib.rs")` into $OUT_DIR/cxxbridge, whose
// parent is on the include path: <crate-name>/<bridge-path>.rs.h. There is no
// hand-written header here — cxx owns this declaration.
#include "rawalchemy_fotlab/src/lib.rs.h"

#include "grading_fused.h"
#include "color_data.h"
#include "lut_applier.h"
#include "metering.h"

#include <algorithm>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <stdexcept>
#include <string>

// Implemented for the `grade` declared in cxxbridge.h (global namespace, the
// default cxx bridge namespace).
//
// The glue is a *thin* pass-through: it starts from upstream's own declared
// defaults (`GradingParams{}`) and overrides ONLY the fields the caller
// explicitly asked for. It deliberately pins no value that upstream owns, so if
// upstream changes a default we follow it automatically — this is the whole
// point of `FOTLAB-RAWLER-000006`.
//
// "Did not ask for this field" is carried across the cxx boundary as an
// out-of-band sentinel, because cxx has no `Option<f32>` / `Option<bool>`:
//   * floats  — quiet NaN means "leave the upstream default"; every finite
//               value (incl. 0.0) is a legitimate override.
//   * boost   — a tri-state int32 (`kBoostUnset` / off / on), so `false` is
//               distinguishable from "unset" (upstream defaults to `true`).
//   * strings — empty means "skip that stage".
namespace {
constexpr int32_t kBoostUnset = -1;
inline bool is_unset(float v) { return std::isnan(v); }
}  // namespace

rust::Vec<float> grade(rust::Slice<const float> data,
                       uint32_t width,
                       uint32_t height,
                       rust::Str log_space,
                       rust::Str lut_path,
                       rust::Str metering_mode,
                       float ev_offset,
                       float target_gray,
                       int32_t enable_boost,
                       float saturation,
                       float contrast,
                       float pivot) {
  using namespace rawalchemy;

  const size_t n = static_cast<size_t>(width) * height * 3u;
  if (data.size() != n) {
    throw std::runtime_error("grade: input length != width*height*3");
  }

  ImageBuffer buf(static_cast<int>(width), static_cast<int>(height), 3);
  std::copy(data.data(), data.data() + static_cast<std::ptrdiff_t>(n), buf.data.begin());

  GradingParams p;

  // --- stage 3+4: gamut transform + log encode (optional) ---
  // An empty name mirrors the upstream C API's null `logSpace`: `logSpaceInfo`
  // keeps its nullptr default and `applyGradingFused` then skips BOTH the gamut
  // matrix and the log OETF (`doGamut = (logSpaceInfo != nullptr)`).
  std::string ls(log_space.data(), log_space.size());
  if (!ls.empty()) {
    auto it = LOG_SPACES.find(ls);
    if (it == LOG_SPACES.end()) {
      throw std::runtime_error("grade: unknown log space '" + ls + "'");
    }
    p.logSpaceInfo = &it->second;
  }

  // --- stage 5: optional 3D LUT ---
  // loadCubeLUT throws std::runtime_error on a bad file; cxx turns that into a
  // Rust `Err(String)` at the FFI boundary.
  LUT3D lut;
  std::string lp(lut_path.data(), lut_path.size());
  if (!lp.empty()) {
    lut = loadCubeLUT(lp);
    p.lut = &lut;
  }

  // --- stage 1: gain, in upstream's own shape: metering (optional) × 2^ev ---
  // Upstream's file-decoding C API meters by default and multiplies by
  // 2^evOffset; we only meter when asked, and the unmetered base stays at unity.
  std::string mm(metering_mode.data(), metering_mode.size());
  float base_gain = 1.0f;
  if (!mm.empty()) {
    if (!isMeteringModeSupported(mm)) {
      throw std::runtime_error("grade: unsupported metering mode '" + mm + "'");
    }
    base_gain = computeAutoGain(buf, mm, is_unset(target_gray) ? 0.18f : target_gray);
  }
  p.gain = base_gain * std::pow(2.0f, ev_offset);

  // --- stage 2: saturation / contrast boost (optional overrides) ---
  if (enable_boost != kBoostUnset) {
    p.enableBoost = (enable_boost != 0);
  }
  if (!is_unset(saturation)) p.saturation = saturation;
  if (!is_unset(contrast)) p.contrast = contrast;
  if (!is_unset(pivot)) p.pivot = pivot;

  applyGradingFused(buf, p);

  rust::Vec<float> out;
  out.reserve(buf.data.size());
  for (float v : buf.data) {
    out.push_back(v);
  }
  return out;
}
