use std::env;
use std::path::Path;

/// Build the `rawalchemy_fotlab` cxx bridge.
///
/// Two pieces of native code get linked into the final cdylib:
///
/// 1. `librawalchemy_grading.a` — built by `cpp/CMakeLists.txt` from ONLY the
///    grading subset of `external/RawAlchemyCpp` (grading_fused / log_transform /
///    lut_applier / metering). No decode, no demosaic, no NN — those pull in
///    LibRaw / ONNX and are intentionally excluded (`FOTLAB-RAWLER-000006`).
/// 2. The cxx-generated bridge + `cpp/rawalchemy_shim.cc`, which assembles a
///    `GradingParams` and calls the public `rawalchemy::applyGradingFused`.
///
/// The RawAlchemyCpp submodule is never modified: every symbol we touch
/// (`applyGradingFused`, `LOG_SPACES`, `loadCubeLUT`, `computeAutoGain`,
/// `GradingParams`, `ImageBuffer`) is part of its public header API.
fn main() {
    // Locate external/RawAlchemyCpp. Allow an override via RAWALCHEMY_SRC; else
    // anchor on the submodule's own header while walking up from this crate.
    //
    // Do NOT count `..` levels here: this crate already moved once (it lives under
    // binding/cxx/, not as a sibling of rawler_fotlab) and a hard-coded count went
    // stale silently — cmake then just failed deep inside with "cannot find source
    // file". Testing for a file we know exists cannot rot the same way.
    let manifest = env!("CARGO_MANIFEST_DIR");
    let rawalchemy_src = env::var("RAWALCHEMY_SRC").unwrap_or_else(|_| {
        Path::new(manifest)
            .ancestors()
            .map(|dir| dir.join("external/RawAlchemyCpp"))
            .find(|cand| cand.join("include/grading_fused.h").is_file())
            .expect(
                "rawalchemy_fotlab: could not locate external/RawAlchemyCpp above \
                 CARGO_MANIFEST_DIR — check the submodule is checked out, or set RAWALCHEMY_SRC",
            )
            .to_string_lossy()
            .into_owned()
    });

    // Target triple (set by cargo per Android ABI). Used both to select the NDK
    // cmake toolchain below and the C++ stdlib later.
    let target = env::var("TARGET").unwrap_or_default();

    // 1. Grading subset -> static lib (cmake crate runs cpp/CMakeLists.txt).
    // When cross-compiling for Android, point cmake at the NDK toolchain so the
    // grading static lib is built for the right ABI; otherwise cmake silently uses
    // the host compiler and the final cargo-ndk link fails with an arch mismatch.
    // `ANDROID_NDK_HOME` is exported by build_rust.yaml.
    // `Config::define` takes `&mut self` and returns `&mut Self`, so the Config has
    // to own a binding of its own — chaining it off `cmake::Config::new()` makes the
    // builder a temporary that dies at the end of the statement while the returned
    // `&mut` is still live (E0716). Keep the two steps separate.
    let mut cmake_cfg = cmake::Config::new("cpp");
    cmake_cfg.define("RAWALCHEMY_SRC", &rawalchemy_src);
    if target.contains("android") {
        let ndk = env::var("ANDROID_NDK_HOME")
            .or_else(|_| env::var("ANDROID_NDK_ROOT"))
            .expect(
                "rawalchemy_fotlab: ANDROID_NDK_HOME/ANDROID_NDK_ROOT must be set to build for Android",
            );
        let toolchain = Path::new(ndk.as_str()).join("build/cmake/android.toolchain.cmake");
        let abi = match target.as_str() {
            "aarch64-linux-android" => "arm64-v8a",
            "armv7-linux-androideabi" => "armeabi-v7a",
            "i686-linux-android" => "x86",
            "x86_64-linux-android" => "x86_64",
            other => panic!("rawalchemy_fotlab: unsupported Android target `{other}`"),
        };
        let min_api = env::var("MIN_API").unwrap_or_else(|_| "26".to_string());
        cmake_cfg
            .define("CMAKE_TOOLCHAIN_FILE", toolchain)
            .define("ANDROID_ABI", abi)
            .define("ANDROID_PLATFORM", format!("android-{min_api}"));
    }
    let dst = cmake_cfg.build();

    // 2. cxx bridge (Rust side generated by cxx-build) + our shim .cc.
    cxx_build::bridge("src/lib.rs")
        .include(format!("{rawalchemy_src}/include"))
        .include("cpp")
        .flag_if_supported("-std=c++17")
        .file("cpp/rawalchemy_shim.cc")
        .compile("rawalchemy_fotlab");

    // Link the grading static lib and the C++ runtime into the final cdylib.
    println!("cargo:rustc-link-search=native={}/lib", dst.display());
    println!("cargo:rustc-link-lib=static=rawalchemy_grading");
    // C++ stdlib: Android NDK links libc++ (`c++`); desktop targets use libstdc++.
    //
    // NOTE: `rustc-link-lib` propagates to the final artifact of a *dependent*
    // crate; `rustc-link-arg` does not (cargo #9554). Since this crate is an rlib
    // consumed by rawler_fotlab's cdylib, only link-lib can carry the runtime.
    // There is no OpenMP link-lib here on purpose: `RA_USE_OPENMP` is never defined
    // for this target, so no `#pragma omp` is compiled and no OMP runtime is needed
    // (see cpp/CMakeLists.txt).
    let cxx_stdlib = if target.contains("android") {
        "c++"
    } else {
        "stdc++"
    };
    println!("cargo:rustc-link-lib=dylib={cxx_stdlib}");

    println!("cargo:rerun-if-changed=cpp/rawalchemy_api.h");
    println!("cargo:rerun-if-changed=cpp/rawalchemy_shim.cc");
    println!("cargo:rerun-if-changed=cpp/CMakeLists.txt");
    println!("cargo:rerun-if-changed=src/lib.rs");
}
