use std::env;
use std::path::Path;

/// Build the `rawalchemy_fotlab` cxx bridge.
///
/// Two pieces of native code get linked into the final cdylib:
///
/// 1. `librawalchemy_grading.a` — built by `cpp/CMakeLists.txt` from ONLY the
///    grading subset of `external/RawAlchemyCpp` (grading_fused / log_transform /
///    lut_applier / metering). No decode, no demosaic, no NN — those pull in
///    LibRaw / ONNX and are intentionally excluded (`FOTLAB-RAWLER-000006`).
/// 2. The cxx-generated bridge + `cpp/rawalchemy_shim.cc`, which assembles a
///    `GradingParams` and calls the public `rawalchemy::applyGradingFused`.
///
/// The RawAlchemyCpp submodule is never modified: every symbol we touch
/// (`applyGradingFused`, `LOG_SPACES`, `loadCubeLUT`, `GradingParams`,
/// `ImageBuffer`) is part of its public header API.
fn main() {
    // Locate external/RawAlchemyCpp. Allow an override via RAWALCHEMY_SRC; else
    // walk up from this crate (app/src/binding/cxx/rawalchemy_fotlab) four levels
    // to the repo root and join external/RawAlchemyCpp.
    let manifest = env!("CARGO_MANIFEST_DIR");
    let repo_root = Path::new(manifest)
        .ancestors()
        .nth(4)
        .expect("rawalchemy_fotlab: could not resolve repo root");
    let rawalchemy_src = env::var("RAWALCHEMY_SRC").unwrap_or_else(|_| {
        repo_root
            .join("external/RawAlchemyCpp")
            .to_string_lossy()
            .into_owned()
    });

    // Target triple (set by cargo per Android ABI). Used both to select the NDK
    // cmake toolchain below and the C++ stdlib later.
    let target = env::var("TARGET").unwrap_or_default();

    // 1. Grading subset -> static lib (cmake crate runs cpp/CMakeLists.txt).
    // When cross-compiling for Android, point cmake at the NDK toolchain so the
    // grading static lib is built for the right ABI; otherwise cmake silently uses
    // the host compiler and the final cargo-ndk link fails with an arch mismatch.
    // `ANDROID_NDK_HOME` is exported by build_rust.yaml.
    let mut cmake_cfg = cmake::Config::new("cpp").define("RAWALCHEMY_SRC", &rawalchemy_src);
    if target.contains("android") {
        let ndk = env::var("ANDROID_NDK_HOME")
            .or_else(|_| env::var("ANDROID_NDK_ROOT"))
            .expect(
                "rawalchemy_fotlab: ANDROID_NDK_HOME/ANDROID_NDK_ROOT must be set to build for Android",
            );
        let toolchain = Path::new(ndk.as_str()).join("build/cmake/android.toolchain.cmake");
        let abi = match target.as_str() {
            "aarch64-linux-android" => "arm64-v8a",
            "armv7-linux-androideabi" => "armeabi-v7a",
            "i686-linux-android" => "x86",
            "x86_64-linux-android" => "x86_64",
            other => panic!("rawalchemy_fotlab: unsupported Android target `{other}`"),
        };
        let min_api = env::var("MIN_API").unwrap_or_else(|_| "26".to_string());
        cmake_cfg = cmake_cfg
            .define("CMAKE_TOOLCHAIN_FILE", toolchain)
            .define("ANDROID_ABI", abi)
            .define("ANDROID_PLATFORM", format!("android-{min_api}"));
    }
    let dst = cmake_cfg.build();

    // 2. cxx bridge (Rust side generated by cxx-build) + our shim .cc.
    cxx_build::bridge("src/lib.rs")
        .include(format!("{rawalchemy_src}/include"))
        .include("cpp")
        .flag_if_supported("-std=c++17")
        .flag_if_supported("-fopenmp")
        .file("cpp/rawalchemy_shim.cc")
        .compile("rawalchemy_fotlab");

    // Link the grading static lib and the C++ runtime into the final cdylib.
    println!("cargo:rustc-link-search=native={}/lib", dst.display());
    println!("cargo:rustc-link-lib=static=rawalchemy_grading");
    // OpenMP runtime (the grading .cpp use `#pragma omp`) for the final link.
    println!("cargo:rustc-link-arg=-fopenmp");
    // C++ stdlib: Android NDK links libc++ (`c++`); desktop targets use libstdc++.
    let cxx_stdlib = if target.contains("android") {
        "c++"
    } else {
        "stdc++"
    };
    println!("cargo:rustc-link-lib=dylib={cxx_stdlib}");

    println!("cargo:rerun-if-changed=cpp/rawalchemy_shim.cc");
    println!("cargo:rerun-if-changed=cpp/CMakeLists.txt");
    println!("cargo:rerun-if-changed=src/lib.rs");
}
