// ===========================================================================
// build.rs — compile the C++ shim and link RawTherapee's `rtengine` static lib.
//
// What this does:
//   1. Compile cxx/rt_demosaic_shim.cc (the C++ adapter) and the cxx-generated
//      bridge glue into a single native lib.
//   2. Add RawTherapee's include directories so the shim can pull in
//      "rawimagesource.h" / "rawimage.h" (which in turn need RT's generated
//      `procparams` headers and the glibmm/lcms2/exiv2/fftw3/libpng/zlib headers).
//   3. Link librtengine.a (built by the Android/NDK build of the RawTherapee
//      submodule) plus its transitive dependencies.
//
// Environment the surrounding build must provide (documented; adjust per target):
//   RAWTHERAPEE_SRC  — root of the RawTherapee submodule (external/RawTherapee).
//                      Used for include paths. procparams is GENERATED by RT's
//                      CMake into the build tree; point this (or add a second
//                      include) at that generated dir if the flat submodule tree
//                      does not carry the generated headers.
//   RAWTHERAPEE_LIB  — directory containing librtengine.a (and the transitive
//                      dependency .a files). Usually the RT CMake build output.
//
// On Android these are wired by the Gradle/Cargo-NDK integration, not set by hand.
// The link lines below are the common transitive set; trim/add per platform once
// you see the actual undefined symbols from librtengine.
// ===========================================================================

fn main() {
    let mut build = cxx::Build::new();

    // The .cc implements the function declared in the cxx bridge (src/lib.rs).
    build.file("cxx/rt_demosaic_shim.cc");
    // Parse the #[cxx::bridge] module so cxx emits the matching C++ glue.
    build.bridge("src/lib.rs");

    // --- RawTherapee include paths ------------------------------------------
    if let Some(rt) = std::env::var_os("RAWTHERAPEE_SRC") {
        let rt = rt.to_string_lossy().into_owned();
        build.include(format!("{rt}/rtengine")); // rawimagesource.h, rawimage.h, array2d.h, ...
        build.include(format!("{rt}/rtexif"));
        build.include(format!("{rt}")); // flat headers (e.g. rtengine/.. fallbacks)
        // If RT's CMake generated `procparams` into a separate build dir, add it here:
        if let Some(gen) = std::env::var_os("RAWTHERAPEE_GEN") {
            build.include(gen.to_string_lossy().into_owned());
        }
    }

    build.flag_if_supported("-std=c++17");
    // RawTherapee is built with OpenMP; match it so the demosaic loops link.
    build.flag_if_supported("-fopenmp");
    build.compile("rt_demosaic_shim");

    // --- Link RawTherapee's rtengine + transitive deps -----------------------
    if let Some(libdir) = std::env::var_os("RAWTHERAPEE_LIB") {
        println!("cargo:rustc-link-search=native={}", libdir.to_string_lossy());
    }
    // rtengine is the static lib we call into (carries RawImageSource::demosaic_external).
    println!("cargo:rustc-link-lib=static=rtengine");
    // Common transitive dependencies of rtengine (verify against your toolchain):
    println!("cargo:rustc-link-lib=static=lcms2");
    println!("cargo:rustc-link-lib=static=exiv2");
    println!("cargo:rustc-link-lib=static=fftw3");
    println!("cargo:rustc-link-lib=static=png");
    println!("cargo:rustc-link-lib=static=z");
    // glibmm / giomm / glib are typically shared on Android; link as needed:
    // println!("cargo:rustc-link-lib=glib-2.0");
    // println!("cargo:rustc-link-lib=glibmm-2.4");
    // OpenMP runtime (clang: omp, gcc: gomp):
    println!("cargo:rustc-link-lib=dylib=gomp");

    // Rebuild when the shim changes.
    println!("cargo:rerun-if-changed=cxx/rt_demosaic_shim.cc");
    println!("cargo:rerun-if-changed=cxx/rt_demosaic_shim.h");
    println!("cargo:rerun-if-changed=src/lib.rs");
    // The RawTherapee hooks (RawImage::set_xtrans + RawImageSource::demosaic_external)
    // must be present in the submodule worktree before building. This repo ships no
    // patch — the hooks are applied manually/out-of-band. See README.md.
}
